package com.qsoft.kata5;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;

/**
 * User: tienhd
 * Date: 8/14/13
 * Time: 9:01 AM
 */
public class HistoryWindow extends JFrame
{
    public static final String HISTORY_WINDOW_NAME = "History Frame";
    private JPanel panel1;
    private JTable tbHistory;

    private HistoryController historyController;

    public HistoryWindow(HistoryController controller)
    {
        super(HISTORY_WINDOW_NAME);
        this.historyController = controller;


        setTitle(HISTORY_WINDOW_NAME);
        setName(HISTORY_WINDOW_NAME);
        setContentPane(panel1);
        pack();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(640, 480);
        setLocation(200, 200);
        setVisible(true);
    }

    public JTable getTbHistory()
    {
        return tbHistory;
    }

    public void setTbHistory(JTable tbHistory)
    {
        this.tbHistory = tbHistory;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        CellConstraints cc = new CellConstraints();
        panel1.add(panel2, cc.xy(1, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel2.add(scrollPane1, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        tbHistory = new JTable();
        tbHistory.setName("tbHistory");
        scrollPane1.setViewportView(tbHistory);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return panel1;
    }
}
