package endtoendtest;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * User: tienhd
 * Date: 8/8/13
 * Time: 8:54 AM
 */
public class MainWindow extends JFrame
{

    public static final String MAIN_WINDOW_NAME = "Tic Tac Toe Main";
    public static final String MAIN_WINDOW_START_BUTTON = "btnStartGame";
    public static final String MAIN_WINDOW_STATUS_LABEL = "lbStatus";
    public static final String MAIN_WINDOW_END_BUTTON = "btnEndGame";

    private JPanel panel1;
    private JLabel lbStatus;
    private JButton btnEndGame;
    private JButton btnStartGame;

    public MainWindow()
    {
        super(MAIN_WINDOW_NAME);
        setTitle(MAIN_WINDOW_NAME);
        setName(MAIN_WINDOW_NAME);

        setContentPane(panel1);
        pack();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(800, 600);
        setVisible(true);
        btnStartGame.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                lbStatus.setText("START");
            }
        });
        btnEndGame.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                lbStatus.setText("END");
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        CellConstraints cc = new CellConstraints();
        panel1.add(panel2, cc.xy(1, 1));
        lbStatus = new JLabel();
        lbStatus.setName("lbStatus");
        lbStatus.setText("lbStatus");
        panel2.add(lbStatus, cc.xy(1, 3));
        btnEndGame = new JButton();
        btnEndGame.setName("btnEndGame");
        btnEndGame.setText("EndGame");
        panel2.add(btnEndGame, cc.xy(3, 1));
        btnStartGame = new JButton();
        btnStartGame.setName("btnStartGame");
        btnStartGame.setText("StartGame");
        panel2.add(btnStartGame, cc.xy(1, 1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return panel1;
    }

}
